// src/data/xpti/typeImages.ts
// Placeholder — images will be generated by ChatHub batch and auto-mapped later via tmp/gen-typeimages.mjs
export const TYPE_IMAGES: Record<string, string> = {};
export const SHARE_IMAGES: Record<string, string> = {};
